const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.Physics,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.LocalStorage.Acts.ClearStorage
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{Solid: 0},
	{Tile: 0},
	{Platform: 0},
	{Flash: 0},
	{Player: 0},
	{Hiasan: 0},
	{Hiasan1: 0},
	{Hiasan2: 0},
	{Keyboard: 0},
	{Physics: 0},
	{Apple: 0},
	{Score: 0},
	{PatrolEnemy: 0},
	{Enemy1: 0},
	{KosonganKanan: 0},
	{KosonganKiri: 0},
	{UIBG: 0},
	{ScoreBase: 0},
	{Coin: 0},
	{RestartButton: 0},
	{Mouse: 0},
	{BGMainMenu: 0},
	{GameOver: 0},
	{MainMenu: 0},
	{HPPic: 0},
	{energy1: 0},
	{energy2: 0},
	{energy3: 0},
	{energy4: 0},
	{energy5: 0},
	{Audio: 0},
	{StartGame: 0},
	{Exit: 0},
	{StartText: 0},
	{ExitText: 0},
	{UsagiDrop: 0},
	{Browser: 0},
	{Resume: 0},
	{SettingButton: 0},
	{HighScoreMainMenu: 0},
	{BGHighScore: 0},
	{HS: 0},
	{HSBG: 0},
	{LocalStorage: 0},
	{Chance: 0},
	{HighScore: 0}
];

self.InstanceType = {
	BG: class extends self.ITiledBackgroundInstance {},
	Tile: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Hiasan: class extends self.ISpriteInstance {},
	Hiasan1: class extends self.ISpriteInstance {},
	Hiasan2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Apple: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	Enemy1: class extends self.ISpriteInstance {},
	KosonganKanan: class extends self.ISpriteInstance {},
	KosonganKiri: class extends self.ISpriteInstance {},
	UIBG: class extends self.ISpriteInstance {},
	ScoreBase: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	RestartButton: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	BGMainMenu: class extends self.ISpriteInstance {},
	GameOver: class extends self.ITextInstance {},
	MainMenu: class extends self.ISpriteInstance {},
	HPPic: class extends self.ISpriteInstance {},
	energy1: class extends self.ISpriteInstance {},
	energy2: class extends self.ISpriteInstance {},
	energy3: class extends self.ISpriteInstance {},
	energy4: class extends self.ISpriteInstance {},
	energy5: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	StartGame: class extends self.ISpriteInstance {},
	Exit: class extends self.ISpriteInstance {},
	StartText: class extends self.ITextInstance {},
	ExitText: class extends self.ITextInstance {},
	UsagiDrop: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	Resume: class extends self.ISpriteInstance {},
	SettingButton: class extends self.ISpriteInstance {},
	HighScoreMainMenu: class extends self.ITextInstance {},
	BGHighScore: class extends self.ISpriteInstance {},
	HS: class extends self.ITextInstance {},
	HSBG: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {}
}